app/src/main/java/com/daon/onjung/ui/profile/ProfileTicketListScreen.kt
closed #3
어떤 변경사항이 있었나요?
- 식권 QR 코드가 제대로 안뜨는 버그 수정
=> #3 Fix : 식권 QR 코드가 제대로 안뜨는 버그 수정

app/build.gradle.kts, app/src/main/java/com/daon/onjung/ui/donation/component/KakaoShare.kt, app/src/main/java/com/daon/onjung/ui/donation/donationResult/DonationResultScreen.kt, gradle/libs.versions.toml
closed #6
어떤 변경사항이 있었나요?
- 작업 내용
- ✨ Feature - 동참하기 결과 공유하기
- N/A
=> ✨ Feature - 동참하기 결과 공유하기

app/src/main/java/com/daon/onjung/network/model/response/OnjungMailListResponse.kt, app/src/main/java/com/daon/onjung/ui/component/ShopMailContainer.kt, app/src/main/java/com/daon/onjung/ui/mail/MailScreen.kt
closed #4 
어떤 변경사항이 있었나요?
- 작업 내용
=> Feat : 온기 우편함 온정 타입에 따른 분기처리

app/src/main/java/com/daon/onjung/ui/home/shopdetail/ShopDetailScreen.kt
closed #12 
어떤 변경사항이 있었나요?
- 작업 내용
=> Feat : 가게 상세 페이지 소개 Introduction 파싱

app/src/main/java/com/daon/onjung/ui/donation/donation/DonationContract.kt, app/src/main/java/com/daon/onjung/ui/donation/donation/DonationScreen.kt, app/src/main/java/com/daon/onjung/ui/donation/donation/DonationViewModel.kt, app/src/main/java/com/daon/onjung/ui/donation/kakaopayPayment/KakaopayPaymentScreen.kt
closed #14 
어떤 변경사항이 있었나요?
- 작업 내용
=> Feat : 카카오페이 분기 처리

app/src/main/java/com/daon/onjung/ui/home/shopdetail/ShopDetailScreen.kt
closed #16 
어떤 변경사항이 있었나요?
- 작업 내용
=> Feat : 가게 상세 X 버튼 삭제

app/src/main/java/com/daon/onjung/ui/CelebrationScreen.kt, app/src/main/java/com/daon/onjung/ui/home/component/OcrFailedDialog.kt, app/src/main/java/com/daon/onjung/ui/home/ocr/OcrCameraContract.kt, app/src/main/java/com/daon/onjung/ui/home/ocr/OcrCameraScreen.kt, app/src/main/java/com/daon/onjung/ui/home/ocr/OcrCameraViewModel.kt, app/src/main/java/com/daon/onjung/ui/home/shopdetail/ShopDetailContract.kt, app/src/main/java/com/daon/onjung/ui/home/shopdetail/ShopDetailScreen.kt, app/src/main/java/com/daon/onjung/ui/home/shopdetail/ShopDetailViewModel.kt
closed #10
어떤 변경사항이 있었나요?
- 온기 공유하기 카카오 공유 연동 및 영수증 불일치 매장 팝업 추가
- N/A
=> Feature - 온기 공유하기 카카오 공유 연동 및 영수증 불일치 매장 팝업 추가

app/src/main/java/com/daon/onjung/ui/profile/ProfileNavigation.kt, app/src/main/java/com/daon/onjung/ui/profile/ProfileScreen.kt, app/src/main/java/com/daon/onjung/ui/profile/ProfileTicketListScreen.kt
closed #18 
어떤 변경사항이 있었나요?
- 작업 내용
=> BugFix : 식당 갯수 오류 수정

app/src/main/java/com/daon/onjung/OnjungNavHost.kt, app/src/main/java/com/daon/onjung/ui/setting/SettingScreen.kt
closed #20
어떤 변경사항이 있었나요?
- 🐞 BugFix - 바텀 시트 노출 오류 및 탈퇴하기 버튼 제거
- N/A
=> 🐞 BugFix - 바텀 시트 노출 오류 및 탈퇴하기 버튼 제거

app/src/main/java/com/daon/onjung/ui/component/ShopMailContainer.kt
closed #23 
어떤 변경사항이 있었나요?
- 작업 내용
=> BugFix : 온기우편함 식권 발송 텍스트 수정

app/src/main/java/com/daon/onjung/OnjungNavHost.kt, app/src/main/java/com/daon/onjung/ui/CelebrationScreen.kt, app/src/main/java/com/daon/onjung/ui/profile/ProfileNavigation.kt, app/src/main/java/com/daon/onjung/ui/profile/ProfileScreen.kt, app/src/main/java/com/daon/onjung/ui/profile/ProfileTicketListContract.kt, app/src/main/java/com/daon/onjung/ui/profile/ProfileTicketListScreen.kt, app/src/main/java/com/daon/onjung/ui/profile/ProfileTicketListViewModel.kt
closed #25
어떤 변경사항이 있었나요?
- 🐞 BugFix - 당첨 페이지 버튼 화면 이동 기능 연동
- N/A
=> 🐞 BugFix - 당첨 페이지 버튼 화면 이동 기능 연동

app/src/main/java/com/daon/onjung/OnjungFCMService.kt, app/src/main/java/com/daon/onjung/OnjungNavHost.kt
closed #28
어떤 변경사항이 있었나요?
- 🐞 BugFix - FCM 백그라운드 수신 시 작동 안되는 버그 수정
- N/A
=> 🐞 BugFix - FCM 백그라운드 수신 시 작동 안되는 버그 수정

app/src/main/java/com/daon/onjung/ui/component/BottomNavigationBar.kt, app/src/main/java/com/daon/onjung/ui/component/TopBar.kt, app/src/main/java/com/daon/onjung/ui/home/component/HomeAppBar.kt, app/src/main/java/com/daon/onjung/ui/profile/ProfileScreen.kt
closed #29 
어떤 변경사항이 있었나요?
- 작업 내용
=> Feature : Topbar shadow 및 Ripple Effect 제거

app/src/main/java/com/daon/onjung/ui/community/component/CommentItem.kt, app/src/main/java/com/daon/onjung/util/ModifierExt.kt
closed #37 
어떤 변경사항이 있었나요?
- 작업 내용
=> Feature : 댓글 컴포넌트 UI 구현

app/src/main/java/com/daon/onjung/ui/community/CommunityContract.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityNavigation.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityViewModel.kt, app/src/main/java/com/daon/onjung/ui/community/CoummnityScreen.kt, app/src/main/java/com/daon/onjung/ui/community/component/CommunityTopBar.kt, app/src/main/java/com/daon/onjung/ui/community/component/PostCardItem.kt
=> Feature : 커뮤니티 스크린 초기 세팅

app/src/main/java/com/daon/onjung/TopLevelDestination.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityDetailScreen.kt, app/src/main/java/com/daon/onjung/ui/community/CoummnityScreen.kt, app/src/main/java/com/daon/onjung/ui/community/component/CommunityTopBar.kt, app/src/main/res/drawable/ic_comment_upload_enabled.xml, app/src/main/res/drawable/ic_plus.xml, app/src/main/res/drawable/ic_post_comment.xml, app/src/main/res/drawable/ic_post_like.xml
closed #48 
어떤 변경사항이 있었나요?
- ✨ Feature - 게시물 상세 화면 디자인 수정
- N/A
=> ✨ Feature - 게시물 상세 화면 디자인 수정

app/src/main/java/com/daon/onjung/data/datasource/SuggestionDataSource.kt, app/src/main/java/com/daon/onjung/data/datasource/SuggestionDataSourceImpl.kt, app/src/main/java/com/daon/onjung/data/repository/SuggestionRepository.kt, app/src/main/java/com/daon/onjung/data/repository/SuggestionRepositoryImpl.kt, app/src/main/java/com/daon/onjung/di/DataModule.kt, app/src/main/java/com/daon/onjung/di/NetworkModule.kt, app/src/main/java/com/daon/onjung/network/service/SuggestionService.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityWriteContract.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityWriteScreen.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityWriteViewModel.kt
closed #50
어떤 변경사항이 있었나요?
- https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_13_FE/issues/50
- N/A
=> ✨ Feature - 가게 추천 게시글 등록 API 연결

app/src/main/java/com/daon/onjung/data/datasource/SuggestionDataSource.kt, app/src/main/java/com/daon/onjung/data/datasource/SuggestionDataSourceImpl.kt, app/src/main/java/com/daon/onjung/data/repository/SuggestionRepository.kt, app/src/main/java/com/daon/onjung/data/repository/SuggestionRepositoryImpl.kt, app/src/main/java/com/daon/onjung/network/model/response/BoardListResponse.kt, app/src/main/java/com/daon/onjung/network/service/SuggestionService.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityContract.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityDetailScreen.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityNavigation.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityViewModel.kt, app/src/main/java/com/daon/onjung/ui/community/CoummnityScreen.kt
closed #53 
어떤 변경사항이 있었나요?
- 게시글 리스트 조회 API 구현
=> Feature : 게시글 리스트 조회 API 구현

app/src/main/java/com/daon/onjung/network/model/CommunityPostStatus.kt, app/src/main/java/com/daon/onjung/network/model/response/BoardListResponse.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityContract.kt, app/src/main/java/com/daon/onjung/ui/community/CommunityViewModel.kt, app/src/main/java/com/daon/onjung/ui/community/CoummnityScreen.kt, app/src/main/java/com/daon/onjung/ui/community/component/PostCardItem.kt
closed #61 
어떤 변경사항이 있었나요?
- 가게 추천 페이지 status 데이터 추가
=> Feat : 가게 추천 페이지 status 데이터 추가

app/src/main/java/com/daon/onjung/ui/community/detail/CommunityDetailScreen.kt
closed #56 
어떤 변경사항이 있었나요?
- https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_13_FE/issues/56
- N/A
=> ✨ Feature - 가게 상세 보기 수정

app/src/main/java/com/daon/onjung/ui/component/imagepicker/ImageLoader.kt, app/src/main/java/com/daon/onjung/ui/component/imagepicker/ImagePickerActivity.kt, app/src/main/java/com/daon/onjung/ui/component/imagepicker/ImagePickerScreen.kt, app/src/main/java/com/daon/onjung/ui/component/imagepicker/ImageRepository.kt, app/src/main/java/com/daon/onjung/ui/component/imagepicker/ImageViewModel.kt
closed #69
어떤 변경사항이 있었나요?
- 다른 이미지를 선택할 때, 기존 선택을 취소하지 않더라도 새로운 이미지로 변경할 수 있도록 설정
- 새로운 사진 찍을 시 해당 이미지 선택
N/A
=> ✨ Feature - 커스텀 갤러리 사진 선택 동작 방식 변경 

app/src/main/java/com/daon/onjung/ui/donation/component/DonationResultCard.kt, app/src/main/java/com/daon/onjung/ui/home/component/HomeBanner.kt, app/src/main/java/com/daon/onjung/ui/home/ocr/OcrCameraScreen.kt, app/src/main/java/com/daon/onjung/ui/home/shopdetail/ShopDetailScreen.kt, app/src/main/java/com/daon/onjung/ui/mail/MailScreen.kt, app/src/main/java/com/daon/onjung/ui/profile/ProfileScreen.kt
closed #71
어떤 변경사항이 있었나요?
- 배너 크기 변경
- 나의 식권 아이콘 변경
- OCR 인증 로딩 로티 애니메이션
- N/A
=> ✨ Feature - 디자인 변경 

app/src/main/java/com/daon/onjung/ui/community/component/CommentItem.kt, app/src/main/java/com/daon/onjung/ui/community/detail/CommunityDetailScreen.kt, app/src/main/java/com/daon/onjung/ui/community/detail/CommunityDetailViewModel.kt, app/src/main/java/com/daon/onjung/ui/component/OnjungLoadingDialog.kt, app/src/main/java/com/daon/onjung/ui/component/ShopCard.kt, app/src/main/java/com/daon/onjung/ui/component/ShopInfoContainer.kt, app/src/main/java/com/daon/onjung/ui/donation/component/DonationSelectPrice.kt, app/src/main/java/com/daon/onjung/ui/donation/kakaopayPayment/KakaopayPaymentScreen.kt, app/src/main/java/com/daon/onjung/ui/home/ocr/OcrCameraScreen.kt, app/src/main/java/com/daon/onjung/ui/profile/component/MealTicketBottomSheet.kt
closed #73 
어떤 변경사항이 있었나요?
- 주소 뒤에 화살표 추가
- 게시글 상세 디자인 수정
- 현금 보유랑 5백만원으로 수정
- 동참 금액 버튼 수정
- 사진으로 저장하기 Ripple Effect 제거
- OCR 영수증 찍을 때 dim 처리
- N/A
=> ✨ Feature - 아몰랑 QA 전부 다
